# Generated by Django 3.2.7 on 2021-09-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_auto_20210917_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
